# backend/app/services/explanation_service.py

from typing import Any, Dict, List, Optional


class ExplanationService:
    """
    Generates clear, citizen-friendly explanations for
    government scheme eligibility results.

    This service does not decide eligibility itself.
    It uses the result produced by EligibilityService /
    RuleEngine and converts it into an understandable explanation.
    """

    def __init__(self, db=None):
        self.db = db

    # ---------------------------------------------------------
    # PUBLIC METHOD
    # ---------------------------------------------------------

    def generate_explanation(
        self,
        scheme: Any,
        eligibility_result: Any,
        citizen_data: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Generate a complete explanation for an eligibility result.

        Parameters
        ----------
        scheme:
            Scheme object/dictionary from Scheme model or schemes.json.

        eligibility_result:
            Result generated by EligibilityService / RuleEngine.

        citizen_data:
            Citizen information used during eligibility checking.

        Returns
        -------
        dict:
            Structured explanation that can be returned by the API.
        """

        scheme_name = self._get_value(
            scheme,
            "name",
            "scheme_name",
            default="Government Scheme",
        )

        eligible = self._get_eligibility_status(eligibility_result)

        reasons = self._get_reasons(eligibility_result)
        failed_conditions = self._get_failed_conditions(eligibility_result)
        passed_conditions = self._get_passed_conditions(eligibility_result)

        if eligible:
            summary = (
                f"Based on the information provided, you appear to "
                f"to meet the eligibility conditions for {scheme_name}."
            )
        else:
            summary = (
                f"Based on the information provided, you do not currently "
                f"meet all the eligibility conditions for {scheme_name}."
            )

        return {
            "scheme_name": scheme_name,
            "eligible": eligible,
            "summary": summary,
            "reasons": reasons,
            "passed_conditions": passed_conditions,
            "failed_conditions": failed_conditions,
            "next_steps": self._generate_next_steps(
                scheme,
                eligible,
                failed_conditions,
            ),
        }

    # ---------------------------------------------------------
    # ELIGIBILITY STATUS
    # ---------------------------------------------------------

    def _get_eligibility_status(self, result: Any) -> bool:
        """
        Extract eligibility status from different possible
        EligibilityResult / RuleEngine result formats.
        """

        value = self._get_value(
            result,
            "eligible",
            "is_eligible",
            "eligibility",
            default=False,
        )

        if isinstance(value, str):
            return value.lower() in {
                "true",
                "yes",
                "eligible",
                "passed",
                "pass",
            }

        return bool(value)

    # ---------------------------------------------------------
    # REASONS
    # ---------------------------------------------------------

    def _get_reasons(self, result: Any) -> List[str]:
        """
        Extract human-readable reasons from the eligibility result.
        """

        reasons = self._get_value(
            result,
            "reasons",
            "explanation",
            "messages",
            default=[],
        )

        if reasons is None:
            return []

        if isinstance(reasons, str):
            return [reasons]

        if isinstance(reasons, list):
            return [str(reason) for reason in reasons]

        return [str(reasons)]

    # ---------------------------------------------------------
    # PASSED CONDITIONS
    # ---------------------------------------------------------

    def _get_passed_conditions(self, result: Any) -> List[Any]:
        """
        Extract conditions successfully satisfied by the citizen.
        """

        conditions = self._get_value(
            result,
            "passed_conditions",
            "passed_rules",
            "matched_rules",
            default=[],
        )

        if conditions is None:
            return []

        if isinstance(conditions, list):
            return conditions

        return [conditions]

    # ---------------------------------------------------------
    # FAILED CONDITIONS
    # ---------------------------------------------------------

    def _get_failed_conditions(self, result: Any) -> List[Any]:
        """
        Extract conditions that were not satisfied.
        """

        conditions = self._get_value(
            result,
            "failed_conditions",
            "failed_rules",
            "unmatched_rules",
            default=[],
        )

        if conditions is None:
            return []

        if isinstance(conditions, list):
            return conditions

        return [conditions]

    # ---------------------------------------------------------
    # NEXT STEPS
    # ---------------------------------------------------------

    def _generate_next_steps(
        self,
        scheme: Any,
        eligible: bool,
        failed_conditions: List[Any],
    ) -> List[str]:
        """
        Generate practical next steps for the citizen.
        """

        if eligible:
            application_url = self._get_value(
                scheme,
                "application_url",
                "apply_url",
                default=None,
            )

            if application_url:
                return [
                    "You can proceed with the scheme application.",
                    f"Apply through the official portal: {application_url}",
                ]

            return [
                "You can proceed with the scheme application.",
                "Verify the required documents before applying.",
                "Use the official government portal to submit your application.",
            ]

        if failed_conditions:
            return [
                "Review the conditions that were not satisfied.",
                "Check whether your information is up to date.",
                "Review the official scheme guidelines for any applicable exceptions.",
            ]

        return [
            "Review the scheme eligibility requirements.",
            "Verify that the information provided is correct.",
            "Check the official government portal for the latest requirements.",
        ]

    # ---------------------------------------------------------
    # VALUE HELPER
    # ---------------------------------------------------------

    @staticmethod
    def _get_value(
        obj: Any,
        *keys: str,
        default: Any = None,
    ) -> Any:
        """
        Read a value from either:
        - dictionary
        - Pydantic model
        - SQLAlchemy model
        - normal Python object
        """

        if obj is None:
            return default

        for key in keys:

            # Dictionary
            if isinstance(obj, dict) and key in obj:
                return obj[key]

            # Normal/Pydantic/SQLAlchemy object
            if hasattr(obj, key):
                value = getattr(obj, key)

                if value is not None:
                    return value

        return default


# -------------------------------------------------------------
# SERVICE INSTANCE
# -------------------------------------------------------------

explanation_service = ExplanationService()